FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app_frontend.py .
COPY ./data ./data

EXPOSE 8501

# Streamlit config commands for running inside a headless cloud instance
CMD ["streamlit", "run", "app_frontend.py", "--server.port=8501", "--server.address=0.0.0.0"]